package xyz.melodysky.runtime.unsafe;

public enum UnsafeOperationKind {
    OBJECT_FIELD_OFFSET,
    STATIC_FIELD_OFFSET,
    ARRAY_BASE_OFFSET,
    ARRAY_INDEX_SCALE,
    GET,
    PUT,
    GET_VOLATILE,
    PUT_VOLATILE,
    COMPARE_AND_SWAP,
    ALLOCATE_INSTANCE,
    VAR_HANDLE_GET,
    VAR_HANDLE_SET,
    VAR_HANDLE_GET_VOLATILE,
    VAR_HANDLE_SET_VOLATILE,
    VAR_HANDLE_COMPARE_AND_SET,
    UNSUPPORTED
}
