package xyz.melodysky.toolchain;

/** Exact invariant tail retained in the sole registration activation. */
final class NativeRegistrationAggregateTailSchema {
    String expected(NativeRegistrationControlTopologyPlan plan) {
        StringBuilder source = new StringBuilder()
                .append("    jthrowable failure_exception = NULL;\n")
                .append("    jthrowable rollback_exception = NULL;\n")
                .append("    jthrowable observed_exception = NULL;\n")
                .append("    jclass rollback_owner = NULL;\n")
                .append("    jboolean rollback_failed = JNI_FALSE;\n")
                .append("    jint unregister_status = JNI_ERR;\n")
                .append("    jint throw_status = JNI_ERR;\n")
                .append("    size_t registered_count = 0u;\n")
                .append("    jclass registered_owners[")
                .append(plan.owners().size())
                .append("] = {NULL};\n")
                .append("    if (")
                .append(plan.chunks().get(0).symbol())
                .append("(env, &resolver, registered_owners, &registered_count) != JNI_OK) {\n")
                .append("        goto rollback;\n")
                .append("    }\n")
                .append("    while (registered_count != 0u) {\n")
                .append("        registered_count--;\n")
                .append("        (*env)->DeleteLocalRef(env, registered_owners[registered_count]);\n")
                .append("        registered_owners[registered_count] = NULL;\n")
                .append("    }\n")
                .append("    j2ll_registration_resolver_close(env, &resolver);\n")
                .append("    return JNI_VERSION_1_8;\n")
                .append("rollback:\n")
                .append("    if ((*env)->ExceptionCheck(env)) {\n")
                .append("        failure_exception = (*env)->ExceptionOccurred(env);\n")
                .append("        (*env)->ExceptionClear(env);\n")
                .append("    }\n")
                .append("    while (registered_count != 0u) {\n")
                .append("        registered_count--;\n")
                .append("        rollback_owner = registered_owners[registered_count];\n")
                .append("        unregister_status = (*env)->UnregisterNatives(env, rollback_owner);\n")
                .append("        if (unregister_status != JNI_OK) {\n")
                .append("            rollback_failed = JNI_TRUE;\n")
                .append("        }\n")
                .append("        if ((*env)->ExceptionCheck(env)) {\n")
                .append("            rollback_failed = JNI_TRUE;\n")
                .append("            observed_exception = (*env)->ExceptionOccurred(env);\n")
                .append("            (*env)->ExceptionClear(env);\n")
                .append("            if (rollback_exception == NULL) {\n")
                .append("                rollback_exception = observed_exception;\n")
                .append("            } else {\n")
                .append("                (*env)->DeleteLocalRef(env, observed_exception);\n")
                .append("            }\n")
                .append("            observed_exception = NULL;\n")
                .append("        }\n")
                .append("        (*env)->DeleteLocalRef(env, rollback_owner);\n")
                .append("        registered_owners[registered_count] = NULL;\n")
                .append("        rollback_owner = NULL;\n")
                .append("    }\n")
                .append("    j2ll_registration_resolver_close(env, &resolver);\n")
                .append("    if (rollback_failed) {\n")
                .append("        if (failure_exception != NULL) {\n")
                .append("            (*env)->DeleteLocalRef(env, failure_exception);\n")
                .append("            failure_exception = NULL;\n")
                .append("        }\n")
                .append("        if (rollback_exception != NULL) {\n")
                .append("            (*env)->DeleteLocalRef(env, rollback_exception);\n")
                .append("            rollback_exception = NULL;\n")
                .append("        }\n")
                .append("        ")
                .append(plan.failureSymbols().aggregateRollback())
                .append("(env);\n")
                .append("        return JNI_ERR;\n")
                .append("    }\n")
                .append("    if (failure_exception != NULL) {\n")
                .append("        throw_status = (*env)->Throw(env, failure_exception);\n")
                .append("        (*env)->DeleteLocalRef(env, failure_exception);\n")
                .append("        failure_exception = NULL;\n")
                .append("        if (throw_status != JNI_OK || !(*env)->ExceptionCheck(env)) {\n")
                .append("            ")
                .append(plan.failureSymbols().aggregateExceptionRestore())
                .append("(env);\n")
                .append("            return JNI_ERR;\n")
                .append("        }\n")
                .append("    }\n")
                .append("    return JNI_ERR;\n");
        return source.toString();
    }
}
