package xyz.melodysky.toolchain;

/** Closed instruction classifications used while collecting final planning evidence. */
enum NativeImplementationEvidenceKind {
    FIELD_ACCESS,
    SUPPORTED_ALLOCATION,
    ALLOCATION_HELPER,
    SUPPORTED_TYPE,
    TYPE_HELPER,
    SUPPORTED_CONSTRUCTOR_CALL,
    CONSTRUCTOR_CALL_HELPER,
    STRING_HELPER,
    STRING_BUILDER_HELPER,
    JDK_SCALAR_HELPER,
    PURE_NATIVE_JDK_HELPER,
    UNSAFE_HELPER,
    VAR_HANDLE_HELPER,
    LAMBDA_HELPER,
    ARITHMETIC_EXCEPTION_HELPER,
    JVM_NUMERIC_HELPER,
    ARRAY_HELPER,
    ARRAYCOPY_HELPER,
    MONITOR_HELPER,
    RUNTIME_METADATA_HELPER,
    CLASS_INIT_HELPER,
    DISPATCH_HELPER,
    SUPPORTED_DISPATCH,
    DIRECT_SPECIAL_CALL,
    SUPPORTED_STATIC_BRIDGE
}
